---
Name: SSPSecurity
After: framework/routes#coreroutes
---
Director:
  rules:
    'Security//$Action/$ID/$OtherID': 'SSPSecurity'
    'security//$Action/$ID/$OtherID': 'SSPSecurity'
    'simplesaml' : 'SSPSecurity' 

